/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116716-g211c88b9d5-20240816"
#endif /* AVUTIL_FFVERSION_H */
